FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
COPY cmd/web ./cmd/web
COPY internal/fmtlog ./internal/fmtlog
RUN CGO_ENABLED=0 GOOS=linux go build -o /web ./cmd/web

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /web /app/web
COPY frontend ./frontend
ENV UI_DIR=./frontend
ENV UI_PORT=3100
EXPOSE 3100
CMD ["/app/web"]
